#!/usr/bin/env Rscript
# =============================================================================
# run_aprl.R
# -----------------------------------------------------------------------------
# Description:
#   Runs the APRL (Automated Paramagnetic Rim Lesion) detection pipeline on a
#   list of subjects. For each subject, the script uses the prlr package to
#   identify paramagnetic rim lesions from a MIMoSA probability map, a binary
#   lesion mask, and a phase image. These inputs are expected to have been
#   generated by run_mimosa_preprocessing.R beforehand.
#
# Usage:
#   Rscript run_aprl.R <sublist_file> <out_root> [lib_path]
#
# Arguments:
#   sublist_file  Path to a text file listing subject IDs, one per line
#                 (e.g. sub-001_ses-01). Subject IDs must include the session
#                 suffix.
#   out_root      Path to the root directory containing preprocessed subject
#                 folders (output of run_mimosa_preprocessing.R)
#   lib_path      (Optional) Path to a custom R library directory if prlr and
#                 its dependencies are installed in a non-default location
#
# Input files required per subject (inside <out_root>/<subject_id>/):
#   - prob.nii.gz              : MIMoSA lesion probability map
#   - prob_50_binary.nii.gz    : binary lesion mask thresholded at 0.5
#   - phase_n4_bet_ws.nii.gz   : WhiteStripe-normalized phase image
#
# Outputs per subject (saved in <out_root>/<subject_id>/aprl/):
#   - findprls_out.RDS     : full output object from prlr::findprls()
#   - aprl_leslabels.nii.gz: labeled lesion mask with PRL predictions
#   - aprl_ria.csv         : rim intensity asymmetry features per lesion
#   - aprl_preds.csv       : PRL predictions per lesion
# =============================================================================

# -----------------------------------------------------------------------------
# Parse command-line arguments
# -----------------------------------------------------------------------------
args <- commandArgs(trailingOnly = TRUE)

if (length(args) < 2) {
  stop("Usage: Rscript run_aprl.R <sublist_file> <out_root> [lib_path]")
}

sublist_file <- args[1]
out_root     <- args[2]
lib_path     <- if (length(args) >= 3) args[3] else NULL

if (!file.exists(sublist_file)) {
  stop("Subject list file does not exist: ", sublist_file)
}

# -----------------------------------------------------------------------------
# Set up custom library path if provided
# -----------------------------------------------------------------------------
if (!is.null(lib_path)) {
  .libPaths(c(lib_path, .libPaths()))
}

# -----------------------------------------------------------------------------
# Load libraries
# -----------------------------------------------------------------------------
suppressPackageStartupMessages({
  library(caret)
  library(prlr)
  library(oro.nifti)
})

# -----------------------------------------------------------------------------
# Read and validate subject list
# -----------------------------------------------------------------------------
subject_list <- readLines(sublist_file, warn = FALSE)
subject_list <- trimws(subject_list)
subject_list <- subject_list[subject_list != ""]
subject_list <- subject_list[!grepl("^#", subject_list)]

if (length(subject_list) == 0) {
  stop("No valid subjects found in subject list file.")
}

cat("Subjects to process:\n")
print(subject_list)

# -----------------------------------------------------------------------------
# Main loop — process each subject
# -----------------------------------------------------------------------------
for (subject_id in subject_list) {
  cat("\n========================================\n")
  cat("Running APRL for:", subject_id, "\n")
  cat("========================================\n")

  reg_out_dir  <- file.path(out_root, subject_id)
  aprl_out_dir <- file.path(reg_out_dir, "aprl")

  # ---------------------------------------------------------------------------
  # Check subject folder exists and create APRL output folder
  # ---------------------------------------------------------------------------
  if (!dir.exists(reg_out_dir)) {
    stop(paste("Missing subject folder:", reg_out_dir))
  }

  if (!dir.exists(aprl_out_dir)) {
    ok <- dir.create(aprl_out_dir, recursive = TRUE, showWarnings = TRUE)
    if (!ok && !dir.exists(aprl_out_dir)) {
      stop(paste("Could not create APRL output folder:", aprl_out_dir))
    }
  }

  # ---------------------------------------------------------------------------
  # Check that all required input files exist
  # ---------------------------------------------------------------------------
  probmap_path <- file.path(reg_out_dir, "prob.nii.gz")
  lesmask_path <- file.path(reg_out_dir, "prob_50_binary.nii.gz")
  phase_path   <- file.path(reg_out_dir, "phase_n4_bet_ws.nii.gz")

  for (p in c(probmap_path, lesmask_path, phase_path)) {
    if (!file.exists(p)) stop(paste("Missing file:", p))
  }

  # ---------------------------------------------------------------------------
  # Load input images and run APRL detection
  # ---------------------------------------------------------------------------
  probmap <- oro.nifti::readNIfTI(probmap_path, reorient = FALSE)
  lesmask <- oro.nifti::readNIfTI(lesmask_path, reorient = FALSE)

  findprls_out <- tryCatch({
    prlr::findprls(
      probmap   = probmap,
      lesmask   = lesmask,
      phasefile = phase_path,
      disc      = TRUE
    )
  }, error = function(e) {
    cat("ERROR for", subject_id, ":", conditionMessage(e), "\n")
    NULL
  })

  # ---------------------------------------------------------------------------
  # Save outputs if APRL ran successfully
  # ---------------------------------------------------------------------------
  if (!is.null(findprls_out)) {

    # Re-check folder just before saving for safety
    if (!dir.exists(aprl_out_dir)) {
      ok <- dir.create(aprl_out_dir, recursive = TRUE, showWarnings = TRUE)
      if (!ok && !dir.exists(aprl_out_dir)) {
        stop(paste("Could not create APRL output folder before saving:", aprl_out_dir))
      }
    }

    # Save full output object
    saveRDS(findprls_out, file.path(aprl_out_dir, "findprls_out.RDS"))

    # Save labeled lesion mask
    oro.nifti::writeNIfTI(findprls_out$leslabels,
                          file.path(aprl_out_dir, "aprl_leslabels"))

    # Save rim intensity asymmetry features per lesion
    write.csv(as.data.frame(findprls_out$ria.df),
              file.path(aprl_out_dir, "aprl_ria.csv"),
              row.names = FALSE)

    # Save PRL predictions per lesion
    write.csv(as.data.frame(findprls_out$preds),
              file.path(aprl_out_dir, "aprl_preds.csv"),
              row.names = FALSE)

    cat("Done:", subject_id, "\n")
    cat("Outputs in:", aprl_out_dir, "\n")
  }
}